perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

install:
  - "cpanm -nq -l local --installdeps --with-develop --with-recommends --with-suggests ."
  - "perl Makefile.PL"
  - "make"
  - "$PWD/local/bin/prove -lvr t"
  - "PERL5LIB=$PWD/local/lib/perl5 PATH=$PWD/local/bin:$PATH perl build.pl"

